### ISSUE TITLE
Android版でMapの移動とスワイプのタブ切り替えのジェスチャーがかぶる

### ISSUE THREAD

**Issue by ayatk** [kiesproject/MawaRouteForRN#14]
Android版はタブメニューをタップしないとタブ切り替えをできないようにしたほうがいいんじゃないかなって思うんだけど、どうっすか

**Comment by nnsnico** [comment]
たしかにそうしたほうがいいかもしれない〜
それかこのUIやめて別のUIにしたほうがいいかな？

**Comment by ayatk** [comment]
ベースのUIは下タブ(?)のままで大丈夫だと思う。というか下タブ以外で良き👏ってなるUIが思いつかない

**Comment by nnsnico** [comment]
とりあえずタブはタップのみ反応するようにします〜:smile:
