### ISSUE TITLE
CIを導入したい

### ISSUE THREAD

**Issue by ayatk** [kiesproject/MawaRouteForRN#19]
- PRの時にlintチェックだったりビルドできるかチェックさせたい
- iOSのCIもやりたいけど、お金かかるのでAndroidだけ

**Comment by nnsnico** [comment]
まるなげする感じで申しわけなんだけど、やってくれると助かります(そして教えてくれると、なおよろこびます)

**Comment by ayatk** [comment]
4月にみんな帰ってきたら勉強会やりたいと思います
