### ISSUE TITLE
ListItemをどうやって選択させるか

### ISSUE THREAD

**Issue by nnsnico** [kiesproject/MawaRouteForRN#21]
CardViewにしたは良いですがこれからどうやってselectableな感じにしましょう

#### よくある実装
- view全体を着色する(ありえそう)
- cardview上部に「選択中」的なテキストを載せる(これもありえそう)
- アニメーションをつける(むずかしそう)

**Comment by ayatk** [comment]
マテリアル感出すの難しいよねぇ...

**Comment by ayatk** [comment]
これ使えないかな
https://facebook.github.io/react-native/docs/touchablenativefeedback.html

**Comment by nnsnico** [comment]
iosは別の実装でやる感じになっちゃうね

**Comment by ayatk** [comment]
追加ボタンみたいなの付けるのが一番現実的かもしれない
![activities-entryactivity-03082018222127](https://user-images.githubusercontent.com/7327867/37153168-2c9f72ae-231f-11e8-92f0-d0ba6e2a6b09.png)

**Comment by nnsnico** [comment]
たしかにこれはかなり現実的:star:これで実装してみましょう

**Comment by ayatk** [comment]
👍
