### ISSUE TITLE
react-native-vector-iconsのエラーで起動しない

### ISSUE THREAD

**Issue by nnsnico** [kiesproject/MawaRouteForRN#25]
- [feature/selectable-list](https://github.com/kiesproject/MawaRouteForRN/tree/feature/selectable-list)内で起きてるエラーです
- 回避する方法はREADMEに記載しましたが、今回もやはりパッケージ内のエラーなのでciが全く意味ない状況になりました。
- VectorIconを扱えるパッケージはこれしかないのでつらみしかない

**Comment by ayatk** [comment]
これって `npm install` のたびに rm しなきゃいけないってこと？

**Comment by nnsnico** [comment]
そういうことになるね、`npm install`するたびにエラーの根源ができちゃうので。実際に開発するなら1回しかインストールしなくていいから1回だけ削除したらいいね

**Comment by ayatk** [comment]
ciのスクリプトいじっちゃダメってわけじゃ無いので、 
https://github.com/kiesproject/MawaRouteForRN/blob/6be93ca9d4a6da267441f6f4e7dbd7607ac2ff43/.circleci/config.yml#L14
の行を
``` yaml
- run: |
  npm install
  rm -rf ./node_modules/react-native/local-cli/core/__fixtures__/files/package.json
```
に書き換えてくれればciはpassすると思う

**Comment by nnsnico** [comment]
ではそのように修正します
