### ISSUE TITLE
ESLint導入したいっす

### ISSUE THREAD

**Issue by ayatk** [kiesproject/MawaRouteForRN#5]
- タイトル通り
- configはairbnb使いたい
- これ無視したいってルールあったら言って欲しい

**Comment by nnsnico** [comment]
ESLintを使うのはとても良いですが、今のコードにlintエラーが起きないように設定してほしいです。
#### 現時点で分かる無視してほしいルール
- stateを使わないcomponentはアロー関数 or functionで実装しなければならない
    - https://qiita.com/koukun/items/e64762e407b8dd5e0247#%E3%82%AF%E3%83%A9%E3%82%B9-vs-reactcreateclass-vs-%E3%82%B9%E3%83%86%E3%83%BC%E3%83%88%E3%83%AC%E3%82%B9
- 命名規則にて、.jsxを推奨すること
    - https://qiita.com/koukun/items/e64762e407b8dd5e0247#%E5%91%BD%E5%90%8D%E8%A6%8F%E5%89%87

**Comment by ayatk** [comment]
了解~
ところで、なんでファイルの拡張子はjsxじゃなくてjsなの？ 🤔

**Comment by nnsnico** [comment]
JSXを書いていないファイルなら.jsで書いてもいいルールがなんかめんどかったので全部.jsに統一にしました:hotsprings:

**Comment by ayatk** [comment]
なるほど理解した
